### create new user
POST http://192.168.8.170:3000/authenticate/register
Content-Type: application/json

{
  "user": {
    "name": "Abdul Aziz",
    "email": "im@abdullaziz.me",
    "password": "Aziz98877449@?",
    "enable": true
  },
  "roleId": "b18556fd-7330-4a24-b164-b6949c686f95"
}

### create new user - online
POST https://api.kwfts.com/authenticate/register
Content-Type: application/json

{
  "user": {
    "name": "Abdul Aziz",
    "email": "im@abdullaziz.me",
    "password": "Aziz98877449@?",
    "enable": true
  },
  "roleId": "c6a99f1c-433b-4ebe-8ca4-d14abebbf94f"
}

### login as admin
POST http://192.168.8.169:3001/authenticate/login
Content-Type: application/json

{
  "email": "im@abdullaziz.me",
  "password": "Aziz98877449@?"
}

### login as business
POST http://192.168.3.8:3000/authenticate/login
Content-Type: application/json

{
  "username": "abdullaziz89@hotmail.com",
  "password": "1234"
}
